function createWordMap(){
  var wordmap = [];
  wordmap["あ"] = [];/*{{{*/
  wordmap["い"] = [];
  wordmap["う"] = [];
  wordmap["え"] = [];
  wordmap["お"] = [];
  wordmap["うぁ"] = [];
  wordmap["うぃ"] = [];
  wordmap["うぇ"] = [];
  wordmap["うぉ"] = [];
  wordmap["ぁ"] = [];
  wordmap["ぃ"] = [];
  wordmap["ぅ"] = [];
  wordmap["ぇ"] = [];
  wordmap["ぉ"] = [];
  wordmap["いぇ"] = [];
  wordmap["か"] = [];
  wordmap["き"] = [];
  wordmap["く"] = [];
  wordmap["け"] = [];
  wordmap["こ"] = [];
  wordmap["きゃ"] = [];
  wordmap["きぃ"] = [];
  wordmap["きゅ"] = [];
  wordmap["きぇ"] = [];
  wordmap["きょ"] = [];
  wordmap["くゃ"] = [];
  wordmap["くゅ"] = [];
  wordmap["くょ"] = [];
  wordmap["くぁ"] = [];
  wordmap["くぃ"] = [];
  wordmap["くぅ"] = [];
  wordmap["くぇ"] = [];
  wordmap["くぉ"] = [];
  wordmap["が"] = [];
  wordmap["ぎ"] = [];
  wordmap["ぐ"] = [];
  wordmap["げ"] = [];
  wordmap["ご"] = [];
  wordmap["ぎゃ"] = [];
  wordmap["ぎぃ"] = [];
  wordmap["ぎゅ"] = [];
  wordmap["ぎぇ"] = [];
  wordmap["ぎょ"] = [];
  wordmap["ぐぁ"] = [];
  wordmap["ぐぃ"] = [];
  wordmap["ぐぅ"] = [];
  wordmap["ぐぇ"] = [];
  wordmap["ぐぉ"] = [];
  wordmap["ヵ"] = [];
  wordmap["ヶ"] = [];
  wordmap["さ"] = [];
  wordmap["し"] = [];
  wordmap["す"] = [];
  wordmap["せ"] = [];
  wordmap["そ"] = [];
  wordmap["しゃ"] = [];
  wordmap["しぃ"] = [];
  wordmap["しゅ"] = [];
  wordmap["しぇ"] = [];
  wordmap["しょ"] = [];
  wordmap["すぁ"] = [];
  wordmap["すぃ"] = [];
  wordmap["すぅ"] = [];
  wordmap["すぇ"] = [];
  wordmap["すぉ"] = [];
  wordmap["ざ"] = [];
  wordmap["じ"] = [];
  wordmap["ず"] = [];
  wordmap["ぜ"] = [];
  wordmap["ぞ"] = [];
  wordmap["じゃ"] = [];
  wordmap["じぃ"] = [];
  wordmap["じゅ"] = [];
  wordmap["じぇ"] = [];
  wordmap["じょ"] = [];
  wordmap["た"] = [];
  wordmap["ち"] = [];
  wordmap["つ"] = [];
  wordmap["て"] = [];
  wordmap["と"] = [];
  wordmap["ちゃ"] = [];
  wordmap["ちぃ"] = [];
  wordmap["ちゅ"] = [];
  wordmap["ちぇ"] = [];
  wordmap["ちょ"] = [];
  wordmap["つぁ"] = [];
  wordmap["つぃ"] = [];
  wordmap["つぇ"] = [];
  wordmap["つぉ"] = [];
  wordmap["てゃ"] = [];
  wordmap["てぃ"] = [];
  wordmap["てゅ"] = [];
  wordmap["てぇ"] = [];
  wordmap["てょ"] = [];
  wordmap["とぁ"] = [];
  wordmap["とぃ"] = [];
  wordmap["とぅ"] = [];
  wordmap["とぇ"] = [];
  wordmap["とぉ"] = [];
  wordmap["だ"] = [];
  wordmap["ぢ"] = [];
  wordmap["づ"] = [];
  wordmap["で"] = [];
  wordmap["ど"] = [];
  wordmap["ぢゃ"] = [];
  wordmap["ぢぃ"] = [];
  wordmap["ぢゅ"] = [];
  wordmap["ぢぇ"] = [];
  wordmap["ぢょ"] = [];
  wordmap["でゃ"] = [];
  wordmap["でぃ"] = [];
  wordmap["でゅ"] = [];
  wordmap["でぇ"] = [];
  wordmap["でょ"] = [];
  wordmap["どぁ"] = [];
  wordmap["どぃ"] = [];
  wordmap["どぅ"] = [];
  wordmap["どぇ"] = [];
  wordmap["どぉ"] = [];
  wordmap["っ"] = [];
  wordmap["な"] = [];
  wordmap["に"] = [];
  wordmap["ぬ"] = [];
  wordmap["ね"] = [];
  wordmap["の"] = [];
  wordmap["にゃ"] = [];
  wordmap["にぃ"] = [];
  wordmap["にゅ"] = [];
  wordmap["にぇ"] = [];
  wordmap["にょ"] = [];
  wordmap["は"] = [];
  wordmap["ひ"] = [];
  wordmap["ふ"] = [];
  wordmap["へ"] = [];
  wordmap["ほ"] = [];
  wordmap["ひゃ"] = [];
  wordmap["ひぃ"] = [];
  wordmap["ひゅ"] = [];
  wordmap["ひぇ"] = [];
  wordmap["ひょ"] = [];
  wordmap["ふぁ"] = [];
  wordmap["ふぃ"] = [];
  wordmap["ふぅ"] = [];
  wordmap["ふぇ"] = [];
  wordmap["ふぉ"] = [];
  wordmap["ふゃ"] = [];
  wordmap["ふゅ"] = [];
  wordmap["ふょ"] = [];
  wordmap["ば"] = [];
  wordmap["び"] = [];
  wordmap["ぶ"] = [];
  wordmap["べ"] = [];
  wordmap["ぼ"] = [];
  wordmap["びゃ"] = [];
  wordmap["びぃ"] = [];
  wordmap["びゅ"] = [];
  wordmap["びぇ"] = [];
  wordmap["びょ"] = [];
  wordmap["ゔぁ"] = [];
  wordmap["ゔぃ"] = [];
  wordmap["ゔ"] = [];
  wordmap["ゔぇ"] = [];
  wordmap["ゔぉ"] = [];
  wordmap["ゔゃ"] = [];
  wordmap["ゔゅ"] = [];
  wordmap["ゔょ"] = [];
  wordmap["ぱ"] = [];
  wordmap["ぴ"] = [];
  wordmap["ぷ"] = [];
  wordmap["ぺ"] = [];
  wordmap["ぽ"] = [];
  wordmap["ぴゃ"] = [];
  wordmap["ぴぃ"] = [];
  wordmap["ぴゅ"] = [];
  wordmap["ぴぇ"] = [];
  wordmap["ぴょ"] = [];
  wordmap["ま"] = [];
  wordmap["み"] = [];
  wordmap["む"] = [];
  wordmap["め"] = [];
  wordmap["も"] = [];
  wordmap["みゃ"] = [];
  wordmap["みぃ"] = [];
  wordmap["みゅ"] = [];
  wordmap["みぇ"] = [];
  wordmap["みょ"] = [];
  wordmap["や"] = [];
  wordmap["ゆ"] = [];
  wordmap["よ"] = [];
  wordmap["ゃ"] = [];
  wordmap["ゅ"] = [];
  wordmap["ょ"] = [];
  wordmap["ら"] = [];
  wordmap["り"] = [];
  wordmap["る"] = [];
  wordmap["れ"] = [];
  wordmap["ろ"] = [];
  wordmap["りゃ"] = [];
  wordmap["りぃ"] = [];
  wordmap["りゅ"] = [];
  wordmap["りぇ"] = [];
  wordmap["りょ"] = [];
  wordmap["わ"] = [];
  wordmap["を"] = [];
  wordmap["っい"] = [];
  wordmap["っう"] = [];
  wordmap["っうぁ"] = [];
  wordmap["っうぃ"] = [];
  wordmap["っうぇ"] = [];
  wordmap["っうぉ"] = [];
  wordmap["っぁ"] = [];
  wordmap["っぃ"] = [];
  wordmap["っぅ"] = [];
  wordmap["っぇ"] = [];
  wordmap["っぉ"] = [];
  wordmap["っいぇ"] = [];
  wordmap["っか"] = [];
  wordmap["っき"] = [];
  wordmap["っく"] = [];
  wordmap["っけ"] = [];
  wordmap["っこ"] = [];
  wordmap["っきゃ"] = [];
  wordmap["っきぃ"] = [];
  wordmap["っきゅ"] = [];
  wordmap["っきぇ"] = [];
  wordmap["っきょ"] = [];
  wordmap["っくゃ"] = [];
  wordmap["っくゅ"] = [];
  wordmap["っくょ"] = [];
  wordmap["っくぁ"] = [];
  wordmap["っくぃ"] = [];
  wordmap["っくぅ"] = [];
  wordmap["っくぇ"] = [];
  wordmap["っくぉ"] = [];
  wordmap["っが"] = [];
  wordmap["っぎ"] = [];
  wordmap["っぐ"] = [];
  wordmap["っげ"] = [];
  wordmap["っご"] = [];
  wordmap["っぎゃ"] = [];
  wordmap["っぎぃ"] = [];
  wordmap["っぎゅ"] = [];
  wordmap["っぎぇ"] = [];
  wordmap["っぎょ"] = [];
  wordmap["っぐぁ"] = [];
  wordmap["っぐぃ"] = [];
  wordmap["っぐぅ"] = [];
  wordmap["っぐぇ"] = [];
  wordmap["っぐぉ"] = [];
  wordmap["っヵ"] = [];
  wordmap["っヶ"] = [];
  wordmap["っさ"] = [];
  wordmap["っし"] = [];
  wordmap["っす"] = [];
  wordmap["っせ"] = [];
  wordmap["っそ"] = [];
  wordmap["っしゃ"] = [];
  wordmap["っしぃ"] = [];
  wordmap["っしゅ"] = [];
  wordmap["っしぇ"] = [];
  wordmap["っしょ"] = [];
  wordmap["っすぁ"] = [];
  wordmap["っすぃ"] = [];
  wordmap["っすぅ"] = [];
  wordmap["っすぇ"] = [];
  wordmap["っすぉ"] = [];
  wordmap["っざ"] = [];
  wordmap["っじ"] = [];
  wordmap["っず"] = [];
  wordmap["っぜ"] = [];
  wordmap["っぞ"] = [];
  wordmap["っじゃ"] = [];
  wordmap["っじぃ"] = [];
  wordmap["っじゅ"] = [];
  wordmap["っじぇ"] = [];
  wordmap["っじょ"] = [];
  wordmap["った"] = [];
  wordmap["っち"] = [];
  wordmap["っつ"] = [];
  wordmap["って"] = [];
  wordmap["っと"] = [];
  wordmap["っちゃ"] = [];
  wordmap["っちぃ"] = [];
  wordmap["っちゅ"] = [];
  wordmap["っちぇ"] = [];
  wordmap["っちょ"] = [];
  wordmap["っつぁ"] = [];
  wordmap["っつぃ"] = [];
  wordmap["っつぇ"] = [];
  wordmap["っつぉ"] = [];
  wordmap["ってゃ"] = [];
  wordmap["ってぃ"] = [];
  wordmap["ってゅ"] = [];
  wordmap["ってぇ"] = [];
  wordmap["ってょ"] = [];
  wordmap["っとぁ"] = [];
  wordmap["っとぃ"] = [];
  wordmap["っとぅ"] = [];
  wordmap["っとぇ"] = [];
  wordmap["っとぉ"] = [];
  wordmap["っだ"] = [];
  wordmap["っぢ"] = [];
  wordmap["っづ"] = [];
  wordmap["っで"] = [];
  wordmap["っど"] = [];
  wordmap["っぢゃ"] = [];
  wordmap["っぢぃ"] = [];
  wordmap["っぢゅ"] = [];
  wordmap["っぢぇ"] = [];
  wordmap["っぢょ"] = [];
  wordmap["っでゃ"] = [];
  wordmap["っでぃ"] = [];
  wordmap["っでゅ"] = [];
  wordmap["っでぇ"] = [];
  wordmap["っでょ"] = [];
  wordmap["っどぁ"] = [];
  wordmap["っどぃ"] = [];
  wordmap["っどぅ"] = [];
  wordmap["っどぇ"] = [];
  wordmap["っどぉ"] = [];
  wordmap["っっ"] = [];
  wordmap["っな"] = [];
  wordmap["っに"] = [];
  wordmap["っぬ"] = [];
  wordmap["っね"] = [];
  wordmap["っの"] = [];
  wordmap["っにゃ"] = [];
  wordmap["っにぃ"] = [];
  wordmap["っにゅ"] = [];
  wordmap["っにぇ"] = [];
  wordmap["っにょ"] = [];
  wordmap["っは"] = [];
  wordmap["っひ"] = [];
  wordmap["っふ"] = [];
  wordmap["っへ"] = [];
  wordmap["っほ"] = [];
  wordmap["っひゃ"] = [];
  wordmap["っひぃ"] = [];
  wordmap["っひゅ"] = [];
  wordmap["っひぇ"] = [];
  wordmap["っひょ"] = [];
  wordmap["っふぁ"] = [];
  wordmap["っふぃ"] = [];
  wordmap["っふぅ"] = [];
  wordmap["っふぇ"] = [];
  wordmap["っふぉ"] = [];
  wordmap["っふゃ"] = [];
  wordmap["っふゅ"] = [];
  wordmap["っふょ"] = [];
  wordmap["っば"] = [];
  wordmap["っび"] = [];
  wordmap["っぶ"] = [];
  wordmap["っべ"] = [];
  wordmap["っぼ"] = [];
  wordmap["っびゃ"] = [];
  wordmap["っびぃ"] = [];
  wordmap["っびゅ"] = [];
  wordmap["っびぇ"] = [];
  wordmap["っびょ"] = [];
  wordmap["っゔぁ"] = [];
  wordmap["っゔぃ"] = [];
  wordmap["っゔ"] = [];
  wordmap["っゔぇ"] = [];
  wordmap["っゔぉ"] = [];
  wordmap["っゔゃ"] = [];
  wordmap["っゔゅ"] = [];
  wordmap["っゔょ"] = [];
  wordmap["っぱ"] = [];
  wordmap["っぴ"] = [];
  wordmap["っぷ"] = [];
  wordmap["っぺ"] = [];
  wordmap["っぽ"] = [];
  wordmap["っぴゃ"] = [];
  wordmap["っぴぃ"] = [];
  wordmap["っぴゅ"] = [];
  wordmap["っぴぇ"] = [];
  wordmap["っぴょ"] = [];
  wordmap["っま"] = [];
  wordmap["っみ"] = [];
  wordmap["っむ"] = [];
  wordmap["っめ"] = [];
  wordmap["っも"] = [];
  wordmap["っみゃ"] = [];
  wordmap["っみぃ"] = [];
  wordmap["っみゅ"] = [];
  wordmap["っみぇ"] = [];
  wordmap["っみょ"] = [];
  wordmap["っや"] = [];
  wordmap["っゆ"] = [];
  wordmap["っよ"] = [];
  wordmap["っゃ"] = [];
  wordmap["っゅ"] = [];
  wordmap["っょ"] = [];
  wordmap["っら"] = [];
  wordmap["っり"] = [];
  wordmap["っる"] = [];
  wordmap["っれ"] = [];
  wordmap["っろ"] = [];
  wordmap["っりゃ"] = [];
  wordmap["っりぃ"] = [];
  wordmap["っりゅ"] = [];
  wordmap["っりぇ"] = [];
  wordmap["っりょ"] = [];
  wordmap["わ"] = [];
  wordmap["を"] = [];
  wordmap["っわ"] = [];
  wordmap["っを"] = [];
  wordmap["ん"] = [];
  wordmap["ゎ"] = [];
  wordmap["っゎ"] = [];/*}}}*/
  wordmap["あ"].push("a");/*{{{*/
  wordmap["い"].push("i");
  wordmap["う"].push("u");
  wordmap["え"].push("e");
  wordmap["お"].push("o");
  wordmap["うぁ"].push("wha");
  wordmap["うぃ"].push("whi");
  wordmap["う"].push("whu");
  wordmap["うぇ"].push("whe");
  wordmap["うぉ"].push("who");
  wordmap["うぃ"].push("wi");
  wordmap["う"].push("wu");
  wordmap["うぇ"].push("we");
  wordmap["ぁ"].push("la");
  wordmap["ぃ"].push("li");
  wordmap["ぅ"].push("lu");
  wordmap["ぇ"].push("le");
  wordmap["ぉ"].push("lo");
  wordmap["ぁ"].push("xa");
  wordmap["ぃ"].push("xi");
  wordmap["ぅ"].push("xu");
  wordmap["ぇ"].push("xe");
  wordmap["ぉ"].push("xo");
  wordmap["ぃ"].push("lyi");
  wordmap["ぇ"].push("lye");
  wordmap["ぃ"].push("xyi");
  wordmap["ぇ"].push("xye");
  wordmap["い"].push("yi");
  wordmap["いぇ"].push("ye");
  wordmap["か"].push("ka");
  wordmap["き"].push("ki");
  wordmap["く"].push("ku");
  wordmap["け"].push("ke");
  wordmap["こ"].push("ko");
  wordmap["か"].push("ca");
  wordmap["く"].push("cu");
  wordmap["こ"].push("co");
  wordmap["きゃ"].push("kya");
  wordmap["きぃ"].push("kyi");
  wordmap["きゅ"].push("kyu");
  wordmap["きぇ"].push("kye");
  wordmap["きょ"].push("kyo");
  wordmap["くゃ"].push("qya");
  wordmap["くぃ"].push("qyi");
  wordmap["くゅ"].push("qyu");
  wordmap["くぇ"].push("qye");
  wordmap["くょ"].push("qyo");
  wordmap["くぁ"].push("qwa");
  wordmap["くぃ"].push("qwi");
  wordmap["くぅ"].push("qwu");
  wordmap["くぇ"].push("qwe");
  wordmap["くぉ"].push("qwo");
  wordmap["くぁ"].push("qa");
  wordmap["くぃ"].push("qi");
  wordmap["く"].push("qu");
  wordmap["くぇ"].push("qe");
  wordmap["くぉ"].push("qo");
  wordmap["くぁ"].push("kwa");
  wordmap["が"].push("ga");
  wordmap["ぎ"].push("gi");
  wordmap["ぐ"].push("gu");
  wordmap["げ"].push("ge");
  wordmap["ご"].push("go");
  wordmap["ぎゃ"].push("gya");
  wordmap["ぎぃ"].push("gyi");
  wordmap["ぎゅ"].push("gyu");
  wordmap["ぎぇ"].push("gye");
  wordmap["ぎょ"].push("gyo");
  wordmap["ぐぁ"].push("gwa");
  wordmap["ぐぃ"].push("gwi");
  wordmap["ぐぅ"].push("gwu");
  wordmap["ぐぇ"].push("gwe");
  wordmap["ぐぉ"].push("gwo");
  wordmap["ヵ"].push("lka");
  wordmap["ヶ"].push("lke");
  wordmap["ヵ"].push("xka");
  wordmap["ヶ"].push("xke");
  wordmap["さ"].push("sa");
  wordmap["し"].push("si");
  wordmap["す"].push("su");
  wordmap["せ"].push("se");
  wordmap["そ"].push("so");
  wordmap["し"].push("ci");
  wordmap["せ"].push("ce");
  wordmap["しゃ"].push("sya");
  wordmap["しぃ"].push("syi");
  wordmap["しゅ"].push("syu");
  wordmap["しぇ"].push("sye");
  wordmap["しょ"].push("syo");
  wordmap["しゃ"].push("sha");
  wordmap["し"].push("shi");
  wordmap["しゅ"].push("shu");
  wordmap["しぇ"].push("she");
  wordmap["しょ"].push("sho");
  wordmap["すぁ"].push("swa");
  wordmap["すぃ"].push("swi");
  wordmap["すぅ"].push("swu");
  wordmap["すぇ"].push("swe");
  wordmap["すぉ"].push("swo");
  wordmap["ざ"].push("za");
  wordmap["じ"].push("zi");
  wordmap["ず"].push("zu");
  wordmap["ぜ"].push("ze");
  wordmap["ぞ"].push("zo");
  wordmap["じゃ"].push("zya");
  wordmap["じぃ"].push("zyi");
  wordmap["じゅ"].push("zyu");
  wordmap["じぇ"].push("zye");
  wordmap["じょ"].push("zyo");
  wordmap["じゃ"].push("ja");
  wordmap["じ"].push("ji");
  wordmap["じゅ"].push("ju");
  wordmap["じぇ"].push("je");
  wordmap["じょ"].push("jo");
  wordmap["じゃ"].push("jya");
  wordmap["じぃ"].push("jyi");
  wordmap["じゅ"].push("jyu");
  wordmap["じぇ"].push("jye");
  wordmap["じょ"].push("jyo");
  wordmap["た"].push("ta");
  wordmap["ち"].push("ti");
  wordmap["つ"].push("tu");
  wordmap["て"].push("te");
  wordmap["と"].push("to");
  wordmap["ちゃ"].push("tya");
  wordmap["ちぃ"].push("tyi");
  wordmap["ちゅ"].push("tyu");
  wordmap["ちぇ"].push("tye");
  wordmap["ちょ"].push("tyo");
  wordmap["ちゃ"].push("cha");
  wordmap["ち"].push("chi");
  wordmap["ちゅ"].push("chu");
  wordmap["ちぇ"].push("che");
  wordmap["ちょ"].push("cho");
  wordmap["つぁ"].push("tsa");
  wordmap["つぃ"].push("tsi");
  wordmap["つ"].push("tsu");
  wordmap["つぇ"].push("tse");
  wordmap["つぉ"].push("tso");
  wordmap["てゃ"].push("tha");
  wordmap["てぃ"].push("thi");
  wordmap["てゅ"].push("thu");
  wordmap["てぇ"].push("the");
  wordmap["てょ"].push("tho");
  wordmap["とぁ"].push("twa");
  wordmap["とぃ"].push("twi");
  wordmap["とぅ"].push("twu");
  wordmap["とぇ"].push("twe");
  wordmap["とぉ"].push("two");
  wordmap["だ"].push("da");
  wordmap["ぢ"].push("di");
  wordmap["づ"].push("du");
  wordmap["で"].push("de");
  wordmap["ど"].push("do");
  wordmap["ぢゃ"].push("dya");
  wordmap["ぢぃ"].push("dyi");
  wordmap["ぢゅ"].push("dyu");
  wordmap["ぢぇ"].push("dye");
  wordmap["ぢょ"].push("dyo");
  wordmap["でゃ"].push("dha");
  wordmap["でぃ"].push("dhi");
  wordmap["でゅ"].push("dhu");
  wordmap["でぇ"].push("dhe");
  wordmap["でょ"].push("dho");
  wordmap["どぁ"].push("dwa");
  wordmap["どぃ"].push("dwi");
  wordmap["どぅ"].push("dwu");
  wordmap["どぇ"].push("dwe");
  wordmap["どぉ"].push("dwo");
  wordmap["っ"].push("ltu");
  wordmap["っ"].push("xtu");
  wordmap["っ"].push("ltsu");
  wordmap["な"].push("na");
  wordmap["に"].push("ni");
  wordmap["ぬ"].push("nu");
  wordmap["ね"].push("ne");
  wordmap["の"].push("no");
  wordmap["にゃ"].push("nya");
  wordmap["にぃ"].push("nyi");
  wordmap["にゅ"].push("nyu");
  wordmap["にぇ"].push("nye");
  wordmap["にょ"].push("nyo");
  wordmap["は"].push("ha");
  wordmap["ひ"].push("hi");
  wordmap["ふ"].push("hu");
  wordmap["へ"].push("he");
  wordmap["ほ"].push("ho");
  wordmap["ひゃ"].push("hya");
  wordmap["ひぃ"].push("hyi");
  wordmap["ひゅ"].push("hyu");
  wordmap["ひぇ"].push("hye");
  wordmap["ひょ"].push("hyo");
  wordmap["ふぁ"].push("fwa");
  wordmap["ふぃ"].push("fwi");
  wordmap["ふぅ"].push("fwu");
  wordmap["ふぇ"].push("fwe");
  wordmap["ふぉ"].push("fwo");
  wordmap["ふぁ"].push("fa");
  wordmap["ふぃ"].push("fi");
  wordmap["ふ"].push("fu");
  wordmap["ふぇ"].push("fe");
  wordmap["ふぉ"].push("fo");
  wordmap["ふゃ"].push("fya");
  wordmap["ふぃ"].push("fyi");
  wordmap["ふゅ"].push("fyu");
  wordmap["ふぇ"].push("fye");
  wordmap["ふょ"].push("fyo");
  wordmap["ば"].push("ba");
  wordmap["び"].push("bi");
  wordmap["ぶ"].push("bu");
  wordmap["べ"].push("be");
  wordmap["ぼ"].push("bo");
  wordmap["びゃ"].push("bya");
  wordmap["びぃ"].push("byi");
  wordmap["びゅ"].push("byu");
  wordmap["びぇ"].push("bye");
  wordmap["びょ"].push("byo");
  wordmap["ゔぁ"].push("va");
  wordmap["ゔぃ"].push("vi");
  wordmap["ゔ"].push("vu");
  wordmap["ゔぇ"].push("ve");
  wordmap["ゔぉ"].push("vo");
  wordmap["ゔゃ"].push("vya");
  wordmap["ゔぃ"].push("vyi");
  wordmap["ゔゅ"].push("vyu");
  wordmap["ゔぇ"].push("vye");
  wordmap["ゔょ"].push("vyo");
  wordmap["ぱ"].push("pa");
  wordmap["ぴ"].push("pi");
  wordmap["ぷ"].push("pu");
  wordmap["ぺ"].push("pe");
  wordmap["ぽ"].push("po");
  wordmap["ぴゃ"].push("pya");
  wordmap["ぴぃ"].push("pyi");
  wordmap["ぴゅ"].push("pyu");
  wordmap["ぴぇ"].push("pye");
  wordmap["ぴょ"].push("pyo");
  wordmap["ま"].push("ma");
  wordmap["み"].push("mi");
  wordmap["む"].push("mu");
  wordmap["め"].push("me");
  wordmap["も"].push("mo");
  wordmap["みゃ"].push("mya");
  wordmap["みぃ"].push("myi");
  wordmap["みゅ"].push("myu");
  wordmap["みぇ"].push("mye");
  wordmap["みょ"].push("myo");
  wordmap["や"].push("ya");
  wordmap["ゆ"].push("yu");
  wordmap["よ"].push("yo");
  wordmap["ゃ"].push("lya");
  wordmap["ゅ"].push("lyu");
  wordmap["ょ"].push("lyo");
  wordmap["ゃ"].push("xya");
  wordmap["ゅ"].push("xyu");
  wordmap["ょ"].push("xyo");
  wordmap["ら"].push("ra");
  wordmap["り"].push("ri");
  wordmap["る"].push("ru");
  wordmap["れ"].push("re");
  wordmap["ろ"].push("ro");
  wordmap["りゃ"].push("rya");
  wordmap["りぃ"].push("ryi");
  wordmap["りゅ"].push("ryu");
  wordmap["りぇ"].push("rye");
  wordmap["りょ"].push("ryo");
  wordmap["わ"].push("wa");
  wordmap["を"].push("wo");
  wordmap["ゎ"].push("lwa");
  wordmap["ゎ"].push("xwa");
  wordmap["っうぁ"].push("wwha");
  wordmap["っうぃ"].push("wwhi");
  wordmap["っう"].push("wwhu");
  wordmap["っうぇ"].push("wwhe");
  wordmap["っうぉ"].push("wwho");
  wordmap["っうぃ"].push("wwi");
  wordmap["っう"].push("wwu");
  wordmap["っうぇ"].push("wwe");
  wordmap["っぁ"].push("lla");
  wordmap["っぃ"].push("lli");
  wordmap["っぅ"].push("llu");
  wordmap["っぇ"].push("lle");
  wordmap["っぉ"].push("llo");
  wordmap["っぁ"].push("xxa");
  wordmap["っぃ"].push("xxi");
  wordmap["っぅ"].push("xxu");
  wordmap["っぇ"].push("xxe");
  wordmap["っぉ"].push("xxo");
  wordmap["っぃ"].push("llyi");
  wordmap["っぇ"].push("llye");
  wordmap["っぃ"].push("xxyi");
  wordmap["っぇ"].push("xxye");
  wordmap["っい"].push("yyi");
  wordmap["っいぇ"].push("yye");
  wordmap["っか"].push("kka");
  wordmap["っき"].push("kki");
  wordmap["っく"].push("kku");
  wordmap["っけ"].push("kke");
  wordmap["っこ"].push("kko");
  wordmap["っか"].push("cca");
  wordmap["っく"].push("ccu");
  wordmap["っこ"].push("cco");
  wordmap["っきゃ"].push("kkya");
  wordmap["っきぃ"].push("kkyi");
  wordmap["っきゅ"].push("kkyu");
  wordmap["っきぇ"].push("kkye");
  wordmap["っきょ"].push("kkyo");
  wordmap["っくゃ"].push("qqya");
  wordmap["っくぃ"].push("qqyi");
  wordmap["っくゅ"].push("qqyu");
  wordmap["っくぇ"].push("qqye");
  wordmap["っくょ"].push("qqyo");
  wordmap["っくぁ"].push("qqwa");
  wordmap["っくぃ"].push("qqwi");
  wordmap["っくぅ"].push("qqwu");
  wordmap["っくぇ"].push("qqwe");
  wordmap["っくぉ"].push("qqwo");
  wordmap["っくぁ"].push("qqa");
  wordmap["っくぃ"].push("qqi");
  wordmap["っく"].push("qqu");
  wordmap["っくぇ"].push("qqe");
  wordmap["っくぉ"].push("qqo");
  wordmap["っくぁ"].push("kkwa");
  wordmap["っが"].push("gga");
  wordmap["っぎ"].push("ggi");
  wordmap["っぐ"].push("ggu");
  wordmap["っげ"].push("gge");
  wordmap["っご"].push("ggo");
  wordmap["っぎゃ"].push("ggya");
  wordmap["っぎぃ"].push("ggyi");
  wordmap["っぎゅ"].push("ggyu");
  wordmap["っぎぇ"].push("ggye");
  wordmap["っぎょ"].push("ggyo");
  wordmap["っぐぁ"].push("ggwa");
  wordmap["っぐぃ"].push("ggwi");
  wordmap["っぐぅ"].push("ggwu");
  wordmap["っぐぇ"].push("ggwe");
  wordmap["っぐぉ"].push("ggwo");
  wordmap["っヵ"].push("llka");
  wordmap["っヶ"].push("llke");
  wordmap["っヵ"].push("xxka");
  wordmap["っヶ"].push("xxke");
  wordmap["っさ"].push("ssa");
  wordmap["っし"].push("ssi");
  wordmap["っす"].push("ssu");
  wordmap["っせ"].push("sse");
  wordmap["っそ"].push("sso");
  wordmap["っし"].push("cci");
  wordmap["っせ"].push("cce");
  wordmap["っしゃ"].push("ssya");
  wordmap["っしぃ"].push("ssyi");
  wordmap["っしゅ"].push("ssyu");
  wordmap["っしぇ"].push("ssye");
  wordmap["っしょ"].push("ssyo");
  wordmap["っしゃ"].push("ssha");
  wordmap["っし"].push("sshi");
  wordmap["っしゅ"].push("sshu");
  wordmap["っしぇ"].push("sshe");
  wordmap["っしょ"].push("ssho");
  wordmap["っすぁ"].push("sswa");
  wordmap["っすぃ"].push("sswi");
  wordmap["っすぅ"].push("sswu");
  wordmap["っすぇ"].push("sswe");
  wordmap["っすぉ"].push("sswo");
  wordmap["っざ"].push("zza");
  wordmap["っじ"].push("zzi");
  wordmap["っず"].push("zzu");
  wordmap["っぜ"].push("zze");
  wordmap["っぞ"].push("zzo");
  wordmap["っじゃ"].push("zzya");
  wordmap["っじぃ"].push("zzyi");
  wordmap["っじゅ"].push("zzyu");
  wordmap["っじぇ"].push("zzye");
  wordmap["っじょ"].push("zzyo");
  wordmap["っじゃ"].push("jja");
  wordmap["っじ"].push("jji");
  wordmap["っじゅ"].push("jju");
  wordmap["っじぇ"].push("jje");
  wordmap["っじょ"].push("jjo");
  wordmap["っじゃ"].push("jjya");
  wordmap["っじぃ"].push("jjyi");
  wordmap["っじゅ"].push("jjyu");
  wordmap["っじぇ"].push("jjye");
  wordmap["っじょ"].push("jjyo");
  wordmap["った"].push("tta");
  wordmap["っち"].push("tti");
  wordmap["っつ"].push("ttu");
  wordmap["って"].push("tte");
  wordmap["っと"].push("tto");
  wordmap["っちゃ"].push("ttya");
  wordmap["っちぃ"].push("ttyi");
  wordmap["っちゅ"].push("ttyu");
  wordmap["っちぇ"].push("ttye");
  wordmap["っちょ"].push("ttyo");
  wordmap["っちゃ"].push("ccha");
  wordmap["っち"].push("cchi");
  wordmap["っちゅ"].push("cchu");
  wordmap["っちぇ"].push("cche");
  wordmap["っちょ"].push("ccho");
  wordmap["っつぁ"].push("ttsa");
  wordmap["っつぃ"].push("ttsi");
  wordmap["っつ"].push("ttsu");
  wordmap["っつぇ"].push("ttse");
  wordmap["っつぉ"].push("ttso");
  wordmap["ってゃ"].push("ttha");
  wordmap["ってぃ"].push("tthi");
  wordmap["ってゅ"].push("tthu");
  wordmap["ってぇ"].push("tthe");
  wordmap["ってょ"].push("ttho");
  wordmap["っとぁ"].push("ttwa");
  wordmap["っとぃ"].push("ttwi");
  wordmap["っとぅ"].push("ttwu");
  wordmap["っとぇ"].push("ttwe");
  wordmap["っとぉ"].push("ttwo");
  wordmap["っだ"].push("dda");
  wordmap["っぢ"].push("ddi");
  wordmap["っづ"].push("ddu");
  wordmap["っで"].push("dde");
  wordmap["っど"].push("ddo");
  wordmap["っぢゃ"].push("ddya");
  wordmap["っぢぃ"].push("ddyi");
  wordmap["っぢゅ"].push("ddyu");
  wordmap["っぢぇ"].push("ddye");
  wordmap["っぢょ"].push("ddyo");
  wordmap["っでゃ"].push("ddha");
  wordmap["っでぃ"].push("ddhi");
  wordmap["っでゅ"].push("ddhu");
  wordmap["っでぇ"].push("ddhe");
  wordmap["っでょ"].push("ddho");
  wordmap["っどぁ"].push("ddwa");
  wordmap["っどぃ"].push("ddwi");
  wordmap["っどぅ"].push("ddwu");
  wordmap["っどぇ"].push("ddwe");
  wordmap["っどぉ"].push("ddwo");
  wordmap["っっ"].push("lltu");
  wordmap["っっ"].push("xxtu");
  wordmap["っっ"].push("lltsu");
  wordmap["っな"].push("nna");
  wordmap["っに"].push("nni");
  wordmap["っぬ"].push("nnu");
  wordmap["っね"].push("nne");
  wordmap["っの"].push("nno");
  wordmap["っにゃ"].push("nnya");
  wordmap["っにぃ"].push("nnyi");
  wordmap["っにゅ"].push("nnyu");
  wordmap["っにぇ"].push("nnye");
  wordmap["っにょ"].push("nnyo");
  wordmap["っは"].push("hha");
  wordmap["っひ"].push("hhi");
  wordmap["っふ"].push("hhu");
  wordmap["っへ"].push("hhe");
  wordmap["っほ"].push("hho");
  wordmap["っひゃ"].push("hhya");
  wordmap["っひぃ"].push("hhyi");
  wordmap["っひゅ"].push("hhyu");
  wordmap["っひぇ"].push("hhye");
  wordmap["っひょ"].push("hhyo");
  wordmap["っふぁ"].push("ffwa");
  wordmap["っふぃ"].push("ffwi");
  wordmap["っふぅ"].push("ffwu");
  wordmap["っふぇ"].push("ffwe");
  wordmap["っふぉ"].push("ffwo");
  wordmap["っふぁ"].push("ffa");
  wordmap["っふぃ"].push("ffi");
  wordmap["っふ"].push("ffu");
  wordmap["っふぇ"].push("ffe");
  wordmap["っふぉ"].push("ffo");
  wordmap["っふゃ"].push("ffya");
  wordmap["っふぃ"].push("ffyi");
  wordmap["っふゅ"].push("ffyu");
  wordmap["っふぇ"].push("ffye");
  wordmap["っふょ"].push("ffyo");
  wordmap["っば"].push("bba");
  wordmap["っび"].push("bbi");
  wordmap["っぶ"].push("bbu");
  wordmap["っべ"].push("bbe");
  wordmap["っぼ"].push("bbo");
  wordmap["っびゃ"].push("bbya");
  wordmap["っびぃ"].push("bbyi");
  wordmap["っびゅ"].push("bbyu");
  wordmap["っびぇ"].push("bbye");
  wordmap["っびょ"].push("bbyo");
  wordmap["っゔぁ"].push("vva");
  wordmap["っゔぃ"].push("vvi");
  wordmap["っゔ"].push("vvu");
  wordmap["っゔぇ"].push("vve");
  wordmap["っゔぉ"].push("vvo");
  wordmap["っゔゃ"].push("vvya");
  wordmap["っゔぃ"].push("vvyi");
  wordmap["っゔゅ"].push("vvyu");
  wordmap["っゔぇ"].push("vvye");
  wordmap["っゔょ"].push("vvyo");
  wordmap["っぱ"].push("ppa");
  wordmap["っぴ"].push("ppi");
  wordmap["っぷ"].push("ppu");
  wordmap["っぺ"].push("ppe");
  wordmap["っぽ"].push("ppo");
  wordmap["っぴゃ"].push("ppya");
  wordmap["っぴぃ"].push("ppyi");
  wordmap["っぴゅ"].push("ppyu");
  wordmap["っぴぇ"].push("ppye");
  wordmap["っぴょ"].push("ppyo");
  wordmap["っま"].push("mma");
  wordmap["っみ"].push("mmi");
  wordmap["っむ"].push("mmu");
  wordmap["っめ"].push("mme");
  wordmap["っも"].push("mmo");
  wordmap["っみゃ"].push("mmya");
  wordmap["っみぃ"].push("mmyi");
  wordmap["っみゅ"].push("mmyu");
  wordmap["っみぇ"].push("mmye");
  wordmap["っみょ"].push("mmyo");
  wordmap["っや"].push("yya");
  wordmap["っゆ"].push("yyu");
  wordmap["っよ"].push("yyo");
  wordmap["っゃ"].push("llya");
  wordmap["っゅ"].push("llyu");
  wordmap["っょ"].push("llyo");
  wordmap["っゃ"].push("xxya");
  wordmap["っゅ"].push("xxyu");
  wordmap["っょ"].push("xxyo");
  wordmap["っら"].push("rra");
  wordmap["っり"].push("rri");
  wordmap["っる"].push("rru");
  wordmap["っれ"].push("rre");
  wordmap["っろ"].push("rro");
  wordmap["っりゃ"].push("rrya");
  wordmap["っりぃ"].push("rryi");
  wordmap["っりゅ"].push("rryu");
  wordmap["っりぇ"].push("rrye");
  wordmap["っりょ"].push("rryo");
  wordmap["っわ"].push("wwa");
  wordmap["っを"].push("wwo");
  wordmap["ん"].push("n");
  wordmap["ん"].push("xn");
  wordmap["ん"].push("nn");
  wordmap["っゎ"].push("lwa");
  wordmap["っゎ"].push("xwa");/*}}}*/

  for(var k in wordmap){/*{{{*/
    if(k.length!=2) continue;
    var lhs = wordmap[k[0]];
    var rhs = wordmap[k[1]];
    lhs.forEach(l =>{
      rhs.forEach(r => {
        wordmap[k].push(l+r);
      });
    });
  }/*}}}*/
  for(var k in wordmap){/*{{{*/
    if(k.length!=3) continue;
    var lhs,rhs;
    lhs = wordmap[k[0]];
    rhs = wordmap[k[1]+k[2]];
    lhs.forEach(l =>{
      rhs.forEach(r => {
        wordmap[k].push(l+r);
      });
    });
    lhs = wordmap[k[0]+k[1]];
    rhs = wordmap[k[2]];
    lhs.forEach(l =>{
      rhs.forEach(r => {
        wordmap[k].push(l+r);
      });
    });
  }/*}}}*/

  for(var k in wordmap){
    wordmap[k].sort()
    wordmap[k].sort((a,b)=>{return a.length-b.length})
  }
  return wordmap;
}
